# Generated by Django 5.0.4 on 2024-04-23 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('contact_email', models.EmailField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=256)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='web.system')),
            ],
            options={
                'unique_together': {('name', 'value', 'system')},
            },
        ),
    ]
