# Generated by Django 5.0.4 on 2024-04-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('name', 'system')},
        ),
    ]
