# Generated by Django 5.0.4 on 2024-04-23 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_variable_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='variables',
            field=models.ManyToManyField(related_name='systems', to='web.variable'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_variables', to='web.system'),
        ),
    ]
