# Generated by Django 5.0.4 on 2024-04-23 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_system_variables_alter_variable_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='variables',
            new_name='system_variables',
        ),
        migrations.AlterField(
            model_name='variable',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='web.system'),
        ),
    ]
