# Generated by Django 5.0.4 on 2024-04-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_variables_system_system_variables_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='system_variables',
            new_name='all_system_variables',
        ),
    ]
