# Generated by Django 5.0.4 on 2024-04-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_system_variables_system_all_system_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='all_system_variables',
        ),
    ]
