# Generated by Django 5.0.6 on 2024-05-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_system_options_alter_variable_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='name',
            new_name='key',
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('key', 'system')},
        ),
    ]
