# Generated by Django 5.0.6 on 2024-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_name_variable_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Chave'),
        ),
    ]
