# Generated by Django 5.0.6 on 2024-05-13 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_variable_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='decrypted_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Valor Decifrado'),
            preserve_default=False,
        ),
    ]
