# Generated by Django 5.0.6 on 2024-05-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_variable_decrypted_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='decrypted_value',
        ),
    ]
